spring:
  main:
    banner-mode: 'off'
  datasource:
    url: jdbc:mysql://rds.mmg.l:3306/auth?useSSL=false
    username: mmgadmin
    password: mmgatpl0408
    driver-class-name: com.mysql.jdbc.Driver
    initialize: false
# HikariCP settings
    hikari: '*'
    connection-timeout: 60000
    maximum-pool-size: 10
    minimum-idle: 3
# Mail configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: mmgatplaanda@gmail.com
    password: karnataka@2016
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    serialization:
      write-date-keys-as-timestamps: false
  http:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB
server:
  port: 8083
  contextPath: /mmg/api
#Spring actuvator settings to disable default ones as it checks email 
management:
  health:
    defaults:
      enabled: false
jwt:
  secret: bKwkuu7eaYs7atMnYaxyz4
  expiry:
    hour: 1
logging:
  level:
    org: 
      springframework: 
        boot: 
          autoconfigure: ERROR
#
# Amazon SNS Topic 
#
aws:
  sns:
    topic:
      interviewstatus: 
        ARN: "arn:aws:sns:ap-south-1:490706196715:AandA"
    accessKey: "AKIAI6XYWNOXIUV42NXA"
    secretKey: "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"
    region: "ap-south-1"
#aws.sns.topicArn = "arn:aws:sns:ap-south-1:490706196715:AandA"
    topicName: "AandA"
    phoneNumberRegex: '^[6-9]\d{9}$'
MMG:
  headerApiKey: MMGATPL
  oauthUrl: https://www.movemygoods.in:8082/mmg/api/
  authUrl: https://www.movemygoods.in:8083/mmg/api/
  adminUrl: https://www.movemygoods.in:8085/mmg/api/
  customerUrl: https://www.movemygoods.in:8087/mmg/api/
  fareUrl: https://www.movemygoods.in:8090/mmg/api/
  franchiseUrl: https://www.movemygoods.in:8086/mmg/api/
  accessKey: AKIAXEQC6LDVS6SYRWCT
  secretKey: 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
  enableSms: "Yes"
  oauthClientId: 822898102471-v7hme872jkl1vm6a6dcpns7c0i4jillj.apps.googleusercontent.com
  oauthClientSecret: -SR8pNgziNozQ1P6tqUsVbvi
  skipToken: app
  franchiseYearOfContract : 3
  otpExpiryInMinutes: 5
  profileSecHeaderKey: 9e497333-0619-4ee9-8d9b-fd2340c320e1
  otpVisible: "No"
  bucketName: production-mmg
