spring:
  main:
    banner-mode: 'off'
  datasource:
    url: jdbc:mysql://localhost:3306/admin?useSSL=false
    username: root
    password: mmg
    driver-class-name: com.mysql.jdbc.Driver
    initialize: false
# HikariCP settings
    hikari: '*'
    connection-timeout: 60000
    maximum-pool-size: 10
    minimum-idle: 3
# Mail configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: mmg_atpl@gmail.com
    password: mysatmmg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    serialization:
      write-date-keys-as-timestamps: false
  http:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB
server:
  port: 8085
  contextPath: /mmg/api
#Spring actuvator settings to disable default ones as it checks email 
management:
  health:
    defaults:
      enabled: false
jwt:
  secret: bKwkuu7eaYs7atMnYaxyz4
  expiry:
    hour: 1
logging:
  level:
    org: 
      springframework: 
        boot: 
          autoconfigure: ERROR
MMG:
  headerApiKey: MMGATPL
  oauthUrl: http://15.207.198.80:8082/mmg/api/
  authUrl: http://15.207.198.80:8083/mmg/api/
  adminUrl: http://13.126.197.2:8085/mmg/api/
  customerUrl: http://13.126.197.2:8087/mmg/api/
  fareUrl: http://13.233.122.112:8090/mmg/api/
  franchiseUrl: http://13.235.20.30:8086/mmg/api/
  accessKey: AKIAXEQC6LDVS6SYRWCT
  secretKey: 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
  enableSms: "Yes"
  skipToken: app
  masterBucket: dev-mmg
  bucketName: dev-mmg
  